### PR TITLE
Fix veraison example

### PR DESCRIPTION
**Pull request by L0czek**
This PR will fix issues with the latest veraison version.

Requires:
* https://github.com/islet-project/remote-attestation/pull/14

### CODE REVIEW

**Comment by jinbpark** [comment]
Is this the fix you mentioned in [this comment](https://github.com/islet-project/islet/issues/391#issuecomment-2456882439)? (it seems so)

**Review by zpzigi754 — APPROVED** [review]
Thank you for fixing the issue!

**Review by hihi-wang — APPROVED** [review]

**Comment by L0czek** [comment]
@jinbpark 
> Is this the fix you mentioned in https://github.com/islet-project/islet/issues/391#issuecomment-2456882439? (it seems so)

Yes it is.

> Can it work with the current [RUN.md](https://github.com/islet-project/islet/blob/main/examples/veraison/RUN.md)? (I mean, RUN.md doesn't have to be changed according to this PR??)

It should, but as ou can see this is a draft as it is not yet completed. I'm currently modifying the app provisioning framework to also work with veraison. @zos and @Havner are now going over the demo instruction and will be fixing any encountered issues. We want to fix veraison in all islet subprojects in one transaction. I will mark the PRs as ready to review when we finish working on it somewhere in the next week or the next two weeks.

**Comment by Havner** [comment]
We've reviewed the `RUN.md` and made several fixes to make it work with latest changes.
The verification succeeds now and everything works. The last thing that I know of that should be done here is to freeze the Veraison service, but I don't know what's the state of upstream fixes.

**Comment by zos** [comment]
> The last thing that I know of that should be done here is to freeze the Veraison service, but I don't know what's the state of upstream fixes. @zos needs to check that.
 For *now* (as Veraison is highly unstable it might change) all the necessary fixes are merged.

**Comment by hihi-wang** [comment]
For me, it's good to merge it. @zpzigi754 , if there is no other issue here, please merge it.

**Pull request merged**
