### PR TITLE
Adapt the repository for the recent /Samsung/ -> /islet-project/ move

### PR DESCRIPTION
**Pull request by Havner**
3 patches:
- /Samsung/ -> /islet-project/ for the main repository readmes
- /Samsung/ -> /islet-project/ for the veraison demo
- 'ISLET' -> 'Islet'

### CODE REVIEW

**Review by bitboom — APPROVED** [review]

**Comment by bitboom** [comment]
Could you please sign your commits? DCO is a requirement for registering this project to CCC.

'''sh
git commit -s
'''

**Review by bokdeuk-jeong — APPROVED** [review]

**Review by bokdeuk-jeong — COMMENTED** [review]
As ISLET is not an acronym, could you please change ISLET to Islet in this PR too? :)

**Comment by Havner** [comment]
> Could you please sign your commits? DCO is a requirement for registering this project to CCC.
> 
> ```shell
> git commit -s ...
> ```

done

**Comment by Havner** [comment]
> As ISLET is not an acronym, could you please change ISLET to Islet in this PR too? :)

Added third commit with the change

**Pull request merged**
